# Generated by Django 4.2.27 on 2025-12-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='complate_at',
            field=models.DateField(null=True),
        ),
    ]
