# Generated by Django 4.2.27 on 2025-12-21 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='todo',
            table='todo_project_todo',
        ),
    ]
