# Generated by Django 4.2.27 on 2025-12-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_complate_todo_complate_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['user', '-created_at'], name='todo_projec_user_id_b29ea0_idx'),
        ),
    ]
