# Generated by Django 4.2.27 on 2025-12-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_todo_projec_user_id_b29ea0_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='complate_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
